
all: example small medium quitebig alsobig

example:
	python main.py input/a_example.in --output output/a_example.txt --solver example

small:
	python main.py input/b_small.in --output output/b_small.txt --solver example

medium:
	python main.py input/c_medium.in --output output/c_medium.txt --solver example

quitebig:
	python main.py input/d_quite_big.in --output output/d_quite_big.txt --solver example

alsobig:
	python main.py input/e_also_big.in --output output/e_also_big.txt --solver example
