
all: A B

A:
	python main.py input/a.txt --output output/a.txt --solver example

B:
	python main.py input/b.txt --output output/b.txt --solver example

C:
	python main.py input/c.txt --output output/c.txt --solver example

D:
	python main.py input/d.txt --output output/d.txt --solver example

E:
	python main.py input/r.txt --output output/e.txt --solver example

F:
	python main.py input/f.txt --output output/f.txt --solver example
